force-app/main/default/objects/property__c/property__c.object-meta.xml
<CustomObject>
    <label>property</label>
    <nameField>
        <label>property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/property__c/fields/Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Unit__c</fullName>
    <label>Price Per Unit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/property__c/fields/Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Property_Name__c</fullName>
    <label>Property Name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Sold Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/propertiesController.cls
public with sharing class propertiesController {

    @AuraEnabled(cacheable=true)
    public static List<Property__c> getProperties(){

        return [

            SELECT
                Id,
                Property_Name__c,
                Location__c,
                Available_Units__c,
                Total_Units__c,
                Price_Per_Unit__c,
                Status__c,
                Property_Image__c

            FROM Property__c

            WHERE Status__c = 'Available'

            ORDER BY Property_Name__c
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Property__c> searchProperties(
        String searchText
    ){

        String searchPattern =
            '%' + searchText + '%';

        return [

            SELECT
                Id,
                Property_Name__c,
                Location__c,
                Available_Units__c,
                Total_Units__c,
                Price_Per_Unit__c,
                Status__c,
                Property_Image__c

            FROM Property__c

            WHERE
                Property_Name__c LIKE :searchPattern
                OR
                Location__c LIKE :searchPattern

            ORDER BY Property_Name__c
        ];
    }

}