force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BookingDailySummaryScheduler.cls
global class BookingDailySummaryScheduler
implements Schedulable {

    global void execute(SchedulableContext sc) {

        Integer totalBookings = 0;
        Integer confirmedBookings = 0;
        Integer cancelledBookings = 0;
        Integer pendingBookings = 0;

        // Aggregate Query
        List<AggregateResult> results = [
            SELECT Status__c status,
                   COUNT(Id) total
            FROM Booking__c
            GROUP BY Status__c
        ];

        for(AggregateResult ar : results){

            String status =
                (String)ar.get('status');

            Integer countValue =
                (Integer)ar.get('total');

            totalBookings += countValue;

            if(status == 'Confirmed'){
                confirmedBookings = countValue;
            }
            else if(status == 'Cancelled'){
                cancelledBookings = countValue;
            }
            else if(status == 'Pending'){
                pendingBookings = countValue;
            }
        }

        String emailBody =
            'Daily Booking Summary\n\n' +
            'Total Bookings : ' + totalBookings + '\n' +
            'Confirmed Bookings : ' + confirmedBookings + '\n' +
            'Cancelled Bookings : ' + cancelledBookings + '\n' +
            'Pending Bookings : ' + pendingBookings;

        Messaging.SingleEmailMessage mail =
            new Messaging.SingleEmailMessage();

        mail.setToAddresses(
            new String[]{
                UserInfo.getUserEmail()
            }
        );

        mail.setSubject(
            'Daily Booking Summary'
        );

        mail.setPlainTextBody(
            emailBody
        );

        Messaging.sendEmail(
            new Messaging.SingleEmailMessage[]{
                mail
            }
        );
    }
}